import { CompendiumCategory as CategoryType } from '@/store/types/compendium/compendium.types';
import { FilterOptions } from './types';

export const LIMIT = 10;

export const FILTER_OPTIONS: Record<CategoryType, FilterOptions> = {
    characters: {
        gender: ['male', 'female', 'n/a', 'hermaphrodite', 'none'],
        eye_color: [
            'blue',
            'brown',
            'yellow',
            'red',
            'black',
            'orange',
            'hazel',
            'pink',
            'green',
            'gold',
            'unknown',
        ],
        hair_color: [
            'blond',
            'brown',
            'black',
            'white',
            'red',
            'auburn',
            'grey',
            'none',
            'unknown',
        ],
        skin_color: [
            'fair',
            'gold',
            'white',
            'blue',
            'light',
            'red',
            'green',
            'tan',
            'brown',
            'pale',
            'metal',
            'dark',
            'unknown',
        ],
    },
    planets: {
        climate: [
            'temperate',
            'tropical',
            'frozen',
            'murky',
            'arid',
            'windy',
            'hot',
            'artificial temperate',
            'frigid',
            'humid',
            'moist',
            'polluted',
            'superheated',
            'subartic',
            'artic',
            'rocky',
            'unknown',
        ],
        terrain: [
            'desert',
            'grasslands',
            'mountains',
            'jungle',
            'rainforests',
            'tundra',
            'ice caves',
            'mountain ranges',
            'swamp',
            'gas giant',
            'forests',
            'lakes',
            'grassy hills',
            'cityscape',
            'ocean',
            'rock',
            'barren',
            'scrublands',
            'savanna',
            'canyons',
            'sinkholes',
            'volcanoes',
            'lava rivers',
            'caves',
            'rivers',
            'airless asteroid',
            'unknown',
        ],
    },
    films: {
        director: [
            'George Lucas',
            'Irvin Kershner',
            'Richard Marquand',
            'J.J. Abrams',
            'Rian Johnson',
        ],
    },
    species: {
        classification: ['mammal', 'artificial', 'reptile', 'sentient', 'amphibian', 'unknown'],
        designation: ['sentient', 'reptilian', 'slave', 'artificial', 'mammal', 'unknown'],
    },
    starships: {
        starship_class: [
            'Starfighter',
            'Deep Space Mobile Battlestation',
            'Light freighter',
            'assault starfighter',
            'Starfighter',
            'Patrol craft',
            'Star dreadnought',
            'Medium transport',
            'unknown',
        ],
    },
    vehicles: {
        vehicle_class: [
            'wheeled',
            'repulsorcraft',
            'starfighter',
            'airspeeder',
            'space/planetary bomber',
            'assault walker',
            'walker',
            'sail barge',
            'unknown',
        ],
        manufacturer: [
            'Corellian Engineering Corporation',
            'Kuat Drive Yards',
            'Sienar Fleet Systems',
            'Kuat Systems Engineering',
            'Nubia Star Drives',
        ],
    },
};

export const FIELD_MAPPING: Record<string, string> = {
    gender: 'gender',
    eye_color: 'eye_color',
    hair_color: 'hair_color',
    skin_color: 'skin_color',
    climate: 'climate',
    terrain: 'terrain',
    director: 'director',
    classification: 'classification',
    designation: 'designation',
    starship_class: 'starship_class',
    vehicle_class: 'vehicle_class',
    manufacturer: 'manufacturer',
};
